library(tidyverse)
library(broom)
library(ggtext)

#### Second Video CC121 ####

#From the raw-data we will look at the shared file rows are the different samples and columns are the different OTUs
#Cells are the abundance
#Data is generated by mothur but not different then how viral contigs in my analysis can sometimes be classified as vOTUs even if multiple viral contigs can represent
#multiple viral species or strains. I digress.

#Note I named my 'raw data' folder differently

shared <- read_tsv("raw_data-0.3/baxter.subsample.shared", col_types = cols(Group = col_character(), .default = col_double())) %>%
  rename_all(tolower) %>%
  select(group, starts_with("otu")) %>% #Add a select to keep group column and remove label and numotus
  pivot_longer(-group, names_to="otu", values_to="count")

#This is the abundance per OTU per group

#Lesson learned: 
#R doesn't like wide dataframes it prefers long dataframes. That it explains things I have done in the past without knowing it.
#Telling read_tsv() the column data types in loading data speeds things up.

#This assigns taxonomy to OTU at the genus level
taxonomy <- read_tsv("raw_data-0.3/baxter.cons.taxonomy") %>%
  rename_all(tolower) %>%
  select(otu, taxonomy) %>% #don't need size
  mutate(otu = tolower(otu), #Mutate to change columns to lower otus to lowercas to match the 'shared' file.
         #Next thing clean taxonomy to get genus level names.
         taxonomy = str_replace_all(taxonomy, "\\(\\d+\\)", ""), #Here we use regex to remove the (100) which tells the percentage of the OTU had that classification
         #An issue with this taxonomy in this version of Mothur output is that everything unclassified is labeled unclassified
         #So despite being different Family-level taxa a genus would still get labled 'unclassified' so we want to change that
         taxonomy = str_replace(taxonomy, ";unclassified", "_unclassified"),
         taxonomy = str_replace_all(taxonomy, ";unclassified", ""),
         taxonomy = str_replace_all(taxonomy, ";$", ""),
         taxonomy = str_replace_all(taxonomy, ".*;", ""))

#Get the metadata
metadata <- read_tsv("raw_data-0.3/baxter.metadata.tsv", col_types=cols(sample = col_character())) %>%
  rename_all(tolower) %>% rename(group = sample) %>%
  #There is a medical condition he is interested in for this data but I don't really understand it. It's fine I think.
  #srn is screen relevant neuplasia or something like that
  #dx_bin has all the diagnosis
  mutate(srn = dx_bin == "Adv Adenoma" | dx_bin == "Cancer", lesion = dx_bin == "Adv Adenoma" | dx_bin == "Cancer" | dx_bin == "Adenoma")          
# OTU counts in themselves are useless, so make a composite table with both OTU and genus.
# Next step is to join the shared and taxonomy dataframes by OTU names thus giving taxonomy to my shared dataframe

composite <- inner_join(shared, taxonomy, by='otu') %>%
  group_by(group, taxonomy) %>%  #Now collapse the same taxonomy by the same sample, i.e. sometimes you can have multiple OTUs with the same genus
  summarize(count = sum(count), .groups="drop") %>%
  group_by(group) %>% mutate(rel_abund = count / sum(count)) %>% #Now that we have counts per group and per taxonomy we then get the relative abundance in new column
  ungroup() %>%
  select(-count) %>% #Removes counts 
  inner_join(., metadata, by="group") #Add in the metadat


#I will write this output to processed data
write.table(composite, file='processed_data/composite.tsv', sep='\t', row.names = FALSE)
